// Re-export core types (these are the foundational types)
export {
  type AgentConfig,
  type BalanceInfo,
  BIFROST_ADAPTER_ABI,
  BIFROST_STRATEGY_LABELS,
  BifrostCurrencyId,
  BifrostOperationError,
  type BifrostProtocolConfig,
  BifrostStrategyType,
  type BifrostYieldProduct,
  type ChainConfig,
  ChainConnectionError,
  ConfigurationError,
  CROSS_CHAIN_ROUTER_ABI,
  type CreateEvmContextOptions,
  type CreatePolkadotContextOptions,
  CrossChainMessageType,
  CrossChainSyncError,
  type CrossChainVaultState,
  createEvmContext,
  createPolkadotContext,
  type DepositParams,
  destroyEvmContext,
  destroyPolkadotContext,
  type KnownChainId,
  type ObiEvmContext,
  ObiKitError,
  type ObiPolkadotContext,
  PolkadotApi,
  type PolkadotSigner,
  SATELLITE_VAULT_ABI,
  type SatelliteChainState,
  type SatelliteVaultConfig,
  SatelliteVaultError,
  ToolInputValidationError,
  type ToolResult,
  type TransactionSigner,
  VAULT_CROSS_CHAIN_ABI,
  type VaultAction,
  type VaultConfig,
  VaultOperationError,
  type VaultRegistry,
  type WithdrawParams,
  XcmError,
  type XcmTransferParams,
} from '@obidot-kit/core';
// Re-export llm types with explicit renames to avoid conflicts
export type {
  AgentConfig as LlmAgentConfig,
  AgentInstance,
  BifrostConfig,
  BifrostStrategyInput,
  BifrostStrategyService,
  BifrostStrategyToolOptions,
  BifrostYieldProviderConfig,
  BifrostYieldToolOptions,
  CrossChainConfig,
  CrossChainRebalanceInput,
  CrossChainRebalanceToolOptions,
  CrossChainStateInput,
  CrossChainStateToolOptions,
  ObiAgentApiConfig,
  ObiBaseToolOptions,
  VaultDepositInput,
  VaultDepositToolOptions,
  VaultWithdrawInput,
  VaultWithdrawToolOptions,
} from '@obidot-kit/llm';

export {
  BifrostStrategyTool,
  BifrostYieldTool,
  CrossChainRebalanceTool,
  CrossChainStateTool,
  createAgent,
  createAgentWithTools,
  ObiAgentApi,
  ObiBaseTool,
  VaultDepositTool,
  VaultWithdrawTool,
} from '@obidot-kit/llm';

// SDK facade
export type { ObiKitConfig } from './obi-kit.js';
export { ObiKit } from './obi-kit.js';
