// Re-export core types (these are the foundational types)
export {
  type AgentConfig,
  type BalanceInfo,
  BIFROST_ADAPTER_ABI,
  BIFROST_STRATEGY_LABELS,
  BifrostCurrencyId,
  BifrostOperationError,
  type BifrostProtocolConfig,
  BifrostStrategyType,
  type BifrostYieldProduct,
  type ChainConfig,
  ChainConnectionError,
  ConfigurationError,
  CROSS_CHAIN_ROUTER_ABI,
  type CreateEvmContextOptions,
  type CreatePolkadotContextOptions,
  type CreateSwapRouterContextOptions,
  CrossChainMessageType,
  CrossChainSyncError,
  type CrossChainVaultState,
  createEvmContext,
  createPolkadotContext,
  createSwapRouterContext,
  type DepositParams,
  type Destination,
  DestType,
  destroyEvmContext,
  destroyPolkadotContext,
  type EvmVaultConfig,
  type IntentAsset,
  type KnownChainId,
  OBIDOT_VAULT_ABI,
  type ObiEvmContext,
  ObiKitError,
  type ObiPolkadotContext,
  type ObiSwapRouterContext,
  ORACLE_REGISTRY_ABI,
  type PerformanceSummary,
  POLKADOT_HUB_TESTNET_RPC,
  POOL_ADAPTER_ABI,
  POOL_TYPE_LABELS,
  PolkadotApi,
  type PolkadotSigner,
  PoolType,
  type ProtocolPerformanceRecord,
  polkadotHubTestnet,
  type Quote,
  type Route,
  SATELLITE_VAULT_ABI,
  type SatelliteChainState,
  type SatelliteVaultConfig,
  SatelliteVaultError,
  type SplitLeg,
  type StrategyIntent,
  type StrategyRecord,
  StrategyStatus,
  SWAP_QUOTER_ABI,
  SWAP_ROUTER_ABI,
  type SwapParams,
  type SwapRouterConfig,
  ToolInputValidationError,
  type ToolResult,
  type TransactionSigner,
  type UniversalIntent,
  VAULT_CROSS_CHAIN_ABI,
  type VaultAction,
  type VaultConfig,
  VaultOperationError,
  type VaultRegistry,
  type WithdrawalRequest,
  type WithdrawParams,
  XCM_PRECOMPILE_ADDRESS,
  XcmError,
  type XcmTransferParams,
} from '@obidot-kit/core';
// Re-export llm types with explicit renames to avoid conflicts
export type {
  AgentConfig as LlmAgentConfig,
  AgentInstance,
  BatchStrategyInput,
  BatchStrategyItem,
  BatchStrategyToolOptions,
  BifrostConfig,
  BifrostStrategyInput,
  BifrostStrategyService,
  BifrostStrategyToolOptions,
  BifrostYieldProviderConfig,
  BifrostYieldToolOptions,
  CrossChainConfig,
  CrossChainRebalanceInput,
  CrossChainRebalanceToolOptions,
  CrossChainStateInput,
  CrossChainStateToolOptions,
  ExecuteIntentInput,
  ExecuteIntentToolOptions,
  ExecuteLocalSwapInput,
  ExecuteLocalSwapToolOptions,
  ObiAgentApiConfig,
  ObiBaseToolOptions,
  OracleCheckInput,
  OracleCheckToolOptions,
  PerformanceInput,
  PerformanceToolOptions,
  RouteHop,
  SwapExecuteInput,
  SwapExecuteToolOptions,
  SwapMultiHopInput,
  SwapMultiHopToolOptions,
  SwapQuoteInput,
  SwapQuoteToolOptions,
  VaultDepositInput,
  VaultDepositToolOptions,
  VaultWithdrawInput,
  VaultWithdrawToolOptions,
  WithdrawalQueueInput,
  WithdrawalQueueToolOptions,
} from '@obidot-kit/llm';

export {
  BatchStrategyTool,
  BifrostStrategyTool,
  BifrostYieldTool,
  CrossChainRebalanceTool,
  CrossChainStateTool,
  createAgent,
  createAgentWithTools,
  ExecuteIntentTool,
  ExecuteLocalSwapTool,
  ObiAgentApi,
  ObiBaseTool,
  OracleCheckTool,
  PerformanceTool,
  SwapExecuteTool,
  SwapMultiHopTool,
  SwapQuoteTool,
  VaultDepositTool,
  VaultWithdrawTool,
  WithdrawalQueueTool,
} from '@obidot-kit/llm';

// SDK facade
export type { ObiKitConfig } from './obi-kit.js';
export { ObiKit } from './obi-kit.js';
